test1:
	/Users/leuschel/svn_root/ecce/ecce_source/ecce_ciao_entry -config minimal sum_32_8_po.pl -i -o ecce_out.pl -pe "go(X)."
test2:
	/Users/leuschel/svn_root/ecce/ecce_source/ecce_ciao_entry -config minimal sum_128_16_po.pl -i -o ecce_out.pl -pe "go(X)."
test3:
	/Users/leuschel/svn_root/ecce/ecce_source/ecce_ciao_entry -config minimal sum_128_32_po.pl -i -o ecce_out.pl -pe "go(X)."
test4:
	/Users/leuschel/svn_root/ecce/ecce_source/ecce_ciao_entry -config minimal sum_128_64_po.pl -i -o ecce_out.pl -pe "go(X)."
test5:
	/Users/leuschel/svn_root/ecce/ecce_source/ecce_ciao_entry -config minimal sum_256_16_po.pl -i -o ecce_out.pl -pe "go(X)."