% Simple test to see how a partial evaluator handles structure sharing.

p(X,f(X,X)).
q1(A, I) :-
	p(A,B), p(B,C), p(C,D), p(D,E), p(E,F), p(F,G), p(G,H), p(H,I).
q2(A, M) :-
	p(A,B), p(B,C), p(C,D), p(D,E), p(E,F), p(F,G), p(G,H), p(H,I),
	p(I,J), p(J,K), p(K,L), p(L,M).
q(A, Y) :-
	p(A,B), p(B,C), p(C,D), p(D,E), p(E,F), p(F,G), p(G,H), p(H,I),
	p(I,J), p(J,K), p(K,L), p(L,M), p(M,N), p(N,O), p(O,P), p(P,Q),
	p(Q,R), p(R,S), p(S,T), p(T,U), p(U,V), p(V,W), p(W,X), p(X,Y).

leftmost(T, X) :- %print(left(T)),nl,
	(   T == f(U,_) ->
		leftmost(U, X)
	;   X = T
	).

test(X) :-
	q(X, T),
	leftmost(T, L),
	write(L), nl.


run(Call) :-
    statistics(runtime,[T1,_]),
	call(Call),
    statistics(runtime,[T2,_]),
    print('Time is '), Tx is T2-T1, print(Tx),print(' ms'),nl,
    statistics(heap,H), print(heap(H)),nl,
    statistics(local_stack,LS), print(local_stack(LS)),nl,
    statistics(global_stack,GS), print(global_stack(GS)),nl.
    
test1(X) :-
    run((q1(X, T), leftmost(T, L))),
	write(L), nl.
test2(X) :-
    run((q2(X, T), leftmost(T, L))),
	write(L), nl.
    
    /* for test1: Time is 10
    
    heap([1262060,975632]) ---> this is the assert database, not really the heap
local_stack([180,785492])
global_stack([2820,2054096]) --> this is really the heap, first value: size used, second: free

| ?- test2(X).
Time is 0 ms
heap([1262060,975632])
local_stack([180,785492])
global_stack([2868,2054048])
*/

test1_pe(X) :-
    run((q1__1(X, T), leftmost(T, L))),
	write(L), nl.
test2_pe(X) :-
    run((q2__1(X, T), leftmost(T, L))),
	write(L), nl.
    
    /* | ?- test1_pe(X).
Time is 0 ms
heap([1262060,975632])
local_stack([180,785492])
global_stack([5784,2051132])


test2
Time is 0 ms
heap([1262060,975632])
local_stack([180,785492])
global_stack([51864,2005052]) */

q1__1(A,f(f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),
      f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),
      f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))))),
      f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
      f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),
      f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),
      f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A)))),f(f(f(f(A,A),
      f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))))),
      f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
      f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
      f(f(A,A),f(A,A))))))),f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),
      f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),
      f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),
      f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),
      f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),
      f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),
      f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),
      f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),
      f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))))))))).
      
      
      
q2__1(A,f(f(f(f(f(f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))))),f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))))),f(f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))))),f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))))))),f(f(f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))))),f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))))),f(f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))))),f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))))))),f(f(f(f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))))),f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))))),f(f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))))),f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))))))),f(f(f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))))),f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))))),f(f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))))),f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))))))))),f(f(f(f(f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),
 f(A,A)),f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))))),f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))))),f(f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))))),f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))))))),f(f(f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))))),f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),
 f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))))),
 f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A)))),
 f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A)))))))),
 f(f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A)))),
 f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))))),
 f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A)))),
 f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A)))))),
 f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A)))),
 f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))))),
 f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A)))),
 f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))))))),
 f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A)))),
 f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))))),
 f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A)))),
 f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A)))))),
 f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A)))),
 f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))))),
 f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A)))),
 f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A)))))))))),
 f(f(f(f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))))),f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))))),f(f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))))),f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))))))),f(f(f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))))),f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))))),f(f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),
 f(f(A,A),f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))))),f(f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))))),f(f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))),f(f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A)))),f(f(f(f(A,A),f(A,A)),f(f(A,A),f(A,A))),f(f(f(A,A),f(A,A)),f(f(A,A),
 f(A,A))))))))))))).

