#------- You should not change ANYTHING in this file ----------------
#------- All customizable options are in the file ../SETTINGS -------
#------- CAUTION: any change in this directory should be also made in the
#------- twin Makefile in ../lib
include ../SETTINGS
include ../SHARED
#---------------------------------------------------------------------------

all:
	cd .. && $(LPMAKECMD) allcontrib

distclean:
	$(SETLOCALCIAO) $(LPMAKE) -l distutils/distclean distclean

