
cplinux:
	tar -cvf ecce.tar Linux/ecce
	gzip ecce.tar
	mv ecce.tar.gz ~asap/public_html/asap-online-demo/meccedownloads/Linux/ecce.tgz

install: 
	cp Mac/ecce.dmg /home/pe/public_html/ecce/meccedownloads/Mac_OSX/
	tar -cvf ecce.tar Linux/ecce
	gzip ecce.tar
	mv ecce.tar.gz /home/pe/public_html/ecce/meccedownloads/Linux/ecce.tgz
