include ../../SETTINGS
include ../../SHARED

exports:
	$(SETLOCALCIAO) $(CIAOC) -x $(CIAOSRC)/lib/compiler/browse_builtins.pl
	$(SETLOCALCIAO) $(CIAOSRC)/lib/compiler/browse_builtins


distclean:
	/bin/rm -rf *.dep *.po *.asr
	/bin/rm -rf TAGS
