#!/bin/bash



Testname=$1
Orig=$2
Spec=$3
Goal=$4
shift
shift
shift 
shift

SpecSetting=-pe
#SpecSetting=-slice




for SpecSetting in -pe -slice -raf
do
echo -n Running test case [$Testname $SpecSetting] ...

../ecce_source/ecce_ciao_entry $Orig $SpecSetting "$Goal." -o $Spec "$@"

cat <<END > $Testname.pl
main([Test]) :-
	(Test == spec ->
	  ensure_loaded('$Spec')
	  ;
	  ensure_loaded('$Orig')
	  ),		 
   statistics(runtime, [T1,_]),
	Goal=$Goal,
	findall(Goal, Goal, Ans), 
	portray_clause(Ans), 
   statistics(runtime, [T2,_]),
   _Time is T2 - T1,
   %format(user_error, "~NCompleted ~w in ~w ms~n", [Test,Time]),	
	halt.

END
##

rm -rf [$Testname].spec
rm -rf [$Testname].orig



exit 0
done
