struct stream_node *insert_new_stream(struct stream_node *new_stream);
BOOL cunify(Argdecl, TAGGED x1, TAGGED x2);
BOOL cunify_args(Argdecl, int arity, TAGGED *pt1, TAGGED *pt2);
ENG_FLT get_float(register TAGGED t);
ENG_INT get_integer(register TAGGED t);
TAGGED bn_call(Argdecl, int (*f) (/* ??? */), TAGGED x, TAGGED y, INSN *op);
TAGGED init_atom_check(char *str);
TAGGED make_float(Argdecl, ENG_FLT i);
TAGGED make_float_check(Argdecl, ENG_FLT i, INSN *op);
TAGGED make_integer(Argdecl, ENG_INT i);
TAGGED make_integer_check(Argdecl, ENG_INT i, INSN *op);
TAGGED make_large(Argdecl, register TAGGED *ptr);
TAGGED make_structure(Argdecl, register TAGGED functor);
TAGGED ptr_to_stream_noalias(Argdecl, register struct stream_node *n);
TAGGED ptr_to_stream(Argdecl, register struct stream_node *n);
struct definition *find_definition(struct sw_on_key **swp, TAGGED term, TAGGED **argl, BOOL insertp);
struct definition *insert_definition(struct sw_on_key **swp, TAGGED tagpname, int arity, BOOL insertp);
struct definition *new_functor(TAGGED tagpname, int arity);
struct definition *parse_definition(TAGGED complex);
struct stream_node *new_stream(TAGGED streamname, char *streammode, FILE *streamfile);
struct stream_node *stream_to_ptr(register TAGGED t, int mode);
struct stream_node *stream_to_ptr_check(register TAGGED t, int mode, int *errcode);
void add_definition(struct sw_on_key **swp, struct sw_on_key_node *node, TAGGED key, struct definition *def);
void expand_sw_on_key(struct sw_on_key **psw, struct try_node *otherwise, BOOL deletep);
void failc(char *mesg);
void numstack_init(Argdecl);
void update_std_streams(void);
void update_stream(register struct stream_node *s, FILE *file);
