asociacion('TEA1','AS','AUCO','TEA1','EL','AUTO','TEA1','EL','COAU','11',_,_,_,_
,_).
asociacion('TEA1','AS','AUFF','TEA1','EL','AUTO','TEA1','EL','FFAL','01',_,_,_,_
,_).
asociacion('TEA1','AS','AUFN','TEA1','EL','AUTO','TEA1','EL','FNAC','01',_,_,_,_
,_).
asociacion('TEA1','AS','AUNO','TEA1','EL','AUTO','TEA1','EL','NOAU','01',_,_,_,_
,_).
asociacion('TEA1','AS','AUOB','TEA1','EL','AUTO','TEA1','EL','OBRA','0N',_,_,_,_
,_).
asociacion('TEA1','AS','CIID','TEA1','EL','CIUD','TEA1','EL','COCI','11',_,_,_,_
,_).
asociacion('TEA1','AS','CINH','TEA1','EL','CIUD','TEA1','EL','NHAB','11',_,_,_,_
,_).
asociacion('TEA1','AS','CINO','TEA1','EL','CIUD','TEA1','EL','NCIU','11',_,_,_,_
,_).
asociacion('TEA1','AS','CITE','TEA1','EL','CIUD','TEA1','EL','TEAT','0N',_,_,_,_
,_).
asociacion('TEA1','AS','OBAU','TEA1','EL','OBRA','TEA1','EL','AUTO','11',_,_,_,_
,_).
asociacion('TEA1','AS','OBED','TEA1','EL','OBRA','TEA1','EL','FPUB','01',_,_,_,_
,_).
asociacion('TEA1','AS','OBEO','TEA1','EL','OBRA','TEA1','EL','ESOB','11',_,_,_,_
,_).
asociacion('TEA1','AS','OBID','TEA1','EL','OBRA','TEA1','EL','COOB','11',_,_,_,_
,_).
asociacion('TEA1','AS','OBTE','TEA1','EL','OBRA','TEA1','EL','TEAT','0N',_,_,_,_
,_).
asociacion('TEA1','AS','OBTI','TEA1','EL','OBRA','TEA1','EL','NOOB','11',_,_,_,_
,_).
asociacion('TEA1','AS','SEAL','TEA1','EL','SESI','TEA1','EL','ALIB','11',_,_,_,_
,_).
asociacion('TEA1','AS','SEFS','TEA1','EL','SESI','TEA1','EL','FSES','11',_,_,_,_
,_).
asociacion('TEA1','AS','SEHS','TEA1','EL','SESI','TEA1','EL','HSES','11',_,_,_,_
,_).
asociacion('TEA1','AS','SEND','TEA1','EL','SESI','TEA1','EL','DURA','11',_,_,_,_
,_).
asociacion('TEA1','AS','SEPR','TEA1','EL','SESI','TEA1','EL','PREC','11',_,_,_,_
,_).
asociacion('TEA1','AS','SETE','TEA1','EL','SESI','TEA1','EL','TEAT','11',_,_,_,_
,_).
asociacion('TEA1','AS','TEAP','TEA1','EL','TEAT','TEA1','EL','FAPE','11',_,_,_,_
,_).
asociacion('TEA1','AS','TEAS','TEA1','EL','TEAT','TEA1','EL','NASI','11',_,_,_,_
,_).
asociacion('TEA1','AS','TECA','TEA1','EL','TEAT','TEA1','EL','CALL','11',_,_,_,_
,_).
asociacion('TEA1','AS','TECI','TEA1','EL','TEAT','TEA1','EL','CIUD','11',_,_,_,_
,_).
asociacion('TEA1','AS','TEIT','TEA1','EL','TEAT','TEA1','EL','COTE','11',_,_,_,_
,_).
asociacion('TEA1','AS','TENO','TEA1','EL','TEAT','TEA1','EL','NOMB','11',_,_,_,_
,_).
asociacion('TEA1','AS','TENU','TEA1','EL','TEAT','TEA1','EL','NUCA','01',_,_,_,_
,_).
asociacion('TEA1','AS','TEOB','TEA1','EL','TEAT','TEA1','EL','OBRA','01',_,_,_,_
,_).
asociacion('TEA1','AS','TEPO','TEA1','EL','TEAT','TEA1','EL','COPO','01',_,_,_,_
,_).
asociacion('TEA1','AS','TESE','TEA1','EL','TEAT','TEA1','EL','SESI','0N',_,_,_,_
,_).
