elemento('CINE','EL','0003',_,_,_).
elemento('RECE','EL','0002',_,_,_).
elemento('RECE','EL','0003',_,_,_).
elemento('RELI','EL','0001',_,_,_).
elemento('TEA1','EL','ALIB',_,_,_).
elemento('TEA1','EL','AUTO',_,_,_).
elemento('TEA1','EL','CALL',_,_,_).
elemento('TEA1','EL','CIUD',_,_,_).
elemento('TEA1','EL','COAU',_,_,_).
elemento('TEA1','EL','COCI',_,_,_).
elemento('TEA1','EL','COOB',_,_,_).
elemento('TEA1','EL','COPO',_,_,_).
elemento('TEA1','EL','COTE',_,_,_).
elemento('TEA1','EL','DURA',_,_,_).
elemento('TEA1','EL','ESOB',_,_,_).
elemento('TEA1','EL','FAPE',_,_,_).
elemento('TEA1','EL','FFAL',_,_,_).
elemento('TEA1','EL','FNAC',_,_,_).
elemento('TEA1','EL','FPUB',_,_,_).
elemento('TEA1','EL','FSES',_,_,_).
elemento('TEA1','EL','HSES',_,_,_).
elemento('TEA1','EL','NASI',_,_,_).
elemento('TEA1','EL','NCIU',_,_,_).
elemento('TEA1','EL','NHAB',_,_,_).
elemento('TEA1','EL','NOAU',_,_,_).
elemento('TEA1','EL','NOMB',_,_,_).
elemento('TEA1','EL','NOOB',_,_,_).
elemento('TEA1','EL','NUCA',_,_,_).
elemento('TEA1','EL','OBRA',_,_,_).
elemento('TEA1','EL','PREC',_,_,_).
elemento('TEA1','EL','SESI',_,_,_).
elemento('TEA1','EL','TEAT',_,_,_).
