valor('TEA1','VA','ALI1','TEA1','EL','SESI',_,_,_,_,_,_,'NU').
valor('TEA1','VA','AUT1','TEA1','EL','NOAU',_,_,_,_,_,_,'TX').
valor('TEA1','VA','AUT2','TEA1','EL','NOAU',_,_,_,_,_,_,'TX').
valor('TEA1','VA','AUT3','TEA1','EL','NOAU',_,_,_,_,_,_,'TX').
valor('TEA1','VA','COAA','TEA1','EL','COAU',_,_,_,_,_,_,'CO').
valor('TEA1','VA','COCI','TEA1','EL','CIUD',_,_,_,_,_,_,'CO').
valor('TEA1','VA','COO1','TEA1','EL','COOB',_,_,_,_,_,_,'CO').
valor('TEA1','VA','COP1','TEA1','EL','COPO',_,_,_,_,_,_,'NU').
valor('TEA1','VA','COT1','TEA1','EL','COTE',_,_,_,_,_,_,'CO').
valor('TEA1','VA','DUR1','TEA1','EL','DURA',_,_,_,_,_,_,'NU').
valor('TEA1','VA','ESOB','TEA1','EL','ESOB',_,_,_,_,_,_,'TX').
valor('TEA1','VA','ESOQ','TEA1','EL','ESOB',_,_,_,_,_,_,'CO').
valor('TEA1','VA','FAP1','TEA1','EL','FAPE',_,_,_,_,_,_,'FX').
valor('TEA1','VA','FFA1','TEA1','EL','FFAL',_,_,_,_,_,_,'FX').
valor('TEA1','VA','FNA1','TEA1','EL','FNAC',_,_,_,_,_,_,'FX').
valor('TEA1','VA','FPU1','TEA1','EL','FPUB',_,_,_,_,_,_,'FX').
valor('TEA1','VA','FSE1','TEA1','EL','FSES',_,_,_,_,_,_,'FX').
valor('TEA1','VA','HSE1','TEA1','EL','HSES',_,_,_,_,_,_,'HO').
valor('TEA1','VA','NAS1','TEA1','EL','NASI',_,_,_,_,_,_,'NU').
valor('TEA1','VA','NHA1','TEA1','EL','NHAB',_,_,_,_,_,_,'NU').
valor('TEA1','VA','NOA1','TEA1','EL','NOAU',_,_,_,_,_,_,'CO').
valor('TEA1','VA','NOC1','TEA1','EL','NCIU',_,_,_,_,_,_,'TX').
valor('TEA1','VA','NOC2','TEA1','EL','NCIU',_,_,_,_,_,_,'TX').
valor('TEA1','VA','NOC3','TEA1','EL','NCIU',_,_,_,_,_,_,'TX').
valor('TEA1','VA','NOC4','TEA1','EL','NCIU',_,_,_,_,_,_,'TX').
valor('TEA1','VA','NOCQ','TEA1','EL','CALL',_,_,_,_,_,_,'CO').
valor('TEA1','VA','NOM1','TEA1','EL','NOMB',_,_,_,_,_,_,'TX').
valor('TEA1','VA','NOM2','TEA1','EL','NOMB',_,_,_,_,_,_,'TX').
valor('TEA1','VA','NOMQ','TEA1','EL','NOMB',_,_,_,_,_,_,'CO').
valor('TEA1','VA','NOO1','TEA1','EL','NOOB',_,_,_,_,_,_,'TX').
valor('TEA1','VA','NOO2','TEA1','EL','NOOB',_,_,_,_,_,_,'TX').
valor('TEA1','VA','NOO3','TEA1','EL','NOOB',_,_,_,_,_,_,'TX').
valor('TEA1','VA','NOO4','TEA1','EL','NOOB',_,_,_,_,_,_,'TX').
valor('TEA1','VA','NOOQ','TEA1','EL','NOOB',_,_,_,_,_,_,'CO').
valor('TEA1','VA','NUC1','TEA1','EL','NUCA',_,_,_,_,_,_,'NU').
valor('TEA1','VA','PRE1','TEA1','EL','PREC',_,_,_,_,_,_,'NU').
