:- initialization(ecce_compile('benchmark.pro')).
:- initialization(ecce_compile('ic-gen.pro')).
:- initialization(ecce_compile('calc_chtree.pro')).              
:- initialization(ecce_compile('index-tools.pro')).
:- initialization(ecce_compile('chtree_tools.pro')).
:- initialization(ecce_compile('modes.pro')).
:- initialization(ecce_compile('code_generator.pro')).
:- initialization(ecce_compile('msv_analysis.pro')).
:- initialization(ecce_compile('dead_code_elimination.pro')).
:- initialization(ecce_compile('parameters.pro')).
:- initialization(ecce_compile('depth_bound.pro')).
:- initialization(ecce_compile('parametric_files.pro')).
:- initialization(ecce_compile('determinate_post_unfold.pro')).
:- initialization(ecce_compile('post_processor.pro')).
:- initialization(ecce_compile('ecce_main.pro')).
:- initialization(ecce_compile('raf-analysis.pro')).
:- initialization(ecce_compile('ecce_sicstus.pro')).
:- initialization(ecce_compile('self_check.pro')).
:- initialization(ecce_compile('front_end.pro')).
:- initialization(ecce_compile('static_conjunction.pro')).
:- initialization(ecce_compile('global_tree.pro')).
:- initialization(ecce_compile('static_dynamic_functors.pro')).
:- initialization(ecce_compile('homeomorphic.pro')).
:- initialization(ecce_compile('unfold_history.pro')).

:- initialization(ecce_compile('bimtools/Environments.pro')).
:- initialization(ecce_compile('bimtools/gensym.pro')).
:- initialization(ecce_compile('bimtools/StdLists.pro')).
:- initialization(ecce_compile('bimtools/instance.pro')).
:- initialization(ecce_compile('bimtools/bd_findall.pro')).
:- initialization(ecce_compile('bimtools/msg.pro')).
:- initialization(ecce_compile('bimtools/claus_database.pro')).
:- initialization(ecce_compile('bimtools/typechecker.pro')).
:- initialization(ecce_compile('bimtools/debugging.pro')).
:- initialization(ecce_compile('bimtools/html_output.pro')).